#
# Copyright (c) 2021-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/ephemeral.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
appVersion: "1.0"
description: A Helm chart for the Carbyne Stack Ephemeral service.
name: ephemeral
version: 0.2.0
keywords:
  - carbyne stack
  - ephemeral
home: https://www.carbynestack.io
sources:
  - https://github.com/carbynestack/ephemeral
